version: "3.8"

services:
  main:
    container_name: shopee-my-scraper
    environment:
      - WEBHOOK_URL=''<your_discord_channel_webhook_URL>'
    build: .
    image: shopee-my-scraper
    restart: unless-stopped
    volumes: 
      - .:/app
